export type SlackCoverageStatus = "supported" | "partial" | "not_started";

export interface SlackCoverageEntry {
  family: string;
  method: string;
  route: string | string[];
  status: SlackCoverageStatus;
  testedBy: string[];
  notes: string;
}

export const slackCoverageMatrix: SlackCoverageEntry[] = [
  {
    family: "auth",
    method: "auth.test",
    route: "POST /api/auth.test",
    status: "supported",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Bearer token auth returns user and team identity.",
  },
  {
    family: "chat",
    method: "chat.postMessage",
    route: "POST /api/chat.postMessage",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts", "slack-events.test.ts"],
    notes:
      "Text, thread replies, blocks, attachments, metadata, formatting flags, unfurl flags, client message ids, and DM user id posting round trip. Full membership checks are future work.",
  },
  {
    family: "chat",
    method: "chat.update",
    route: "POST /api/chat.update",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts", "slack-events.test.ts"],
    notes: "Stored text and rich message fields are updated and message_changed events are dispatched.",
  },
  {
    family: "chat",
    method: "chat.delete",
    route: "POST /api/chat.delete",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts", "slack-events.test.ts"],
    notes: "Stored messages are deleted and message_deleted events are dispatched.",
  },
  {
    family: "chat",
    method: "chat.getPermalink",
    route: ["GET /api/chat.getPermalink", "POST /api/chat.getPermalink"],
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Returns deterministic emulator permalinks for top-level messages and threaded replies.",
  },
  {
    family: "chat",
    method: "chat.postEphemeral",
    route: "POST /api/chat.postEphemeral",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Stores ephemeral messages outside channel history and validates target channel membership.",
  },
  {
    family: "chat",
    method: "chat.scheduleMessage",
    route: "POST /api/chat.scheduleMessage",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Stores pending scheduled messages with rich payload fields and validates post_at bounds.",
  },
  {
    family: "chat",
    method: "chat.deleteScheduledMessage",
    route: "POST /api/chat.deleteScheduledMessage",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Deletes pending scheduled messages by channel and scheduled message id.",
  },
  {
    family: "chat",
    method: "chat.scheduledMessages.list",
    route: "POST /api/chat.scheduledMessages.list",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Lists pending scheduled messages with channel, time range, and simple cursor filters.",
  },
  {
    family: "chat",
    method: "chat.meMessage",
    route: "POST /api/chat.meMessage",
    status: "partial",
    testedBy: ["slack.test.ts"],
    notes: "Creates a me_message subtype for channels.",
  },
  {
    family: "conversations",
    method: "conversations.list",
    route: "POST /api/conversations.list",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Lists conversations with simple cursor pagination, exclude_archived, and basic public/private/IM/MPIM type filtering.",
  },
  {
    family: "conversations",
    method: "conversations.info",
    route: "POST /api/conversations.info",
    status: "supported",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Returns seeded channel metadata.",
  },
  {
    family: "conversations",
    method: "conversations.create",
    route: "POST /api/conversations.create",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Creates public or private channels and rejects duplicate names.",
  },
  {
    family: "conversations",
    method: "conversations.archive",
    route: "POST /api/conversations.archive",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts", "slack-events.test.ts"],
    notes:
      "Archives channels, excludes them from list results, and dispatches channel_archive or group_archive lifecycle events.",
  },
  {
    family: "conversations",
    method: "conversations.unarchive",
    route: "POST /api/conversations.unarchive",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts", "slack-events.test.ts"],
    notes:
      "Unarchives channels, adds the caller back to membership when needed, and dispatches channel_unarchive or group_unarchive lifecycle events.",
  },
  {
    family: "conversations",
    method: "conversations.rename",
    route: "POST /api/conversations.rename",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts", "slack-events.test.ts"],
    notes:
      "Renames member-visible channels with basic Slack name validation and dispatches channel_rename or group_rename events.",
  },
  {
    family: "conversations",
    method: "conversations.setTopic",
    route: "POST /api/conversations.setTopic",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts", "slack-events.test.ts"],
    notes:
      "Updates channel topic metadata, validates membership and length, and dispatches channel_topic or group_topic messages.",
  },
  {
    family: "conversations",
    method: "conversations.setPurpose",
    route: "POST /api/conversations.setPurpose",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts", "slack-events.test.ts"],
    notes:
      "Updates channel purpose metadata, validates membership and length, and dispatches channel_purpose or group_purpose messages.",
  },
  {
    family: "conversations",
    method: "conversations.history",
    route: "POST /api/conversations.history",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Returns top level messages for a channel, including rich message fields. Time filtering is future work.",
  },
  {
    family: "conversations",
    method: "conversations.replies",
    route: "POST /api/conversations.replies",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Returns parent and replies for a thread, including rich message fields.",
  },
  {
    family: "conversations",
    method: "conversations.join",
    route: "POST /api/conversations.join",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Adds the auth user to channel membership.",
  },
  {
    family: "conversations",
    method: "conversations.leave",
    route: "POST /api/conversations.leave",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Removes the auth user from channel membership.",
  },
  {
    family: "conversations",
    method: "conversations.members",
    route: "POST /api/conversations.members",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Returns channel member ids with empty next cursor.",
  },
  {
    family: "conversations",
    method: "conversations.invite",
    route: "POST /api/conversations.invite",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts", "slack-events.test.ts"],
    notes: "Adds users to public/private channels and MPIMs, with basic membership errors and member_joined_channel events.",
  },
  {
    family: "conversations",
    method: "conversations.kick",
    route: "POST /api/conversations.kick",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts", "slack-events.test.ts"],
    notes: "Removes users from public/private channels and MPIMs, with basic errors and member_left_channel events.",
  },
  {
    family: "conversations",
    method: "conversations.open",
    route: "POST /api/conversations.open",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts", "slack-events.test.ts"],
    notes: "Opens or resumes IM and MPIM conversations by user list or existing conversation id.",
  },
  {
    family: "conversations",
    method: "conversations.close",
    route: "POST /api/conversations.close",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts", "slack-events.test.ts"],
    notes: "Closes IM and MPIM conversations and reports already_closed no-op responses.",
  },
  {
    family: "conversations",
    method: "conversations.mark",
    route: "POST /api/conversations.mark",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts", "slack-events.test.ts"],
    notes: "Stores per-user read cursors for conversations and dispatches marked events.",
  },
  {
    family: "users",
    method: "users.list",
    route: "POST /api/users.list",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Lists active users with simple cursor pagination.",
  },
  {
    family: "users",
    method: "users.info",
    route: "POST /api/users.info",
    status: "supported",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Returns seeded user profile data.",
  },
  {
    family: "users",
    method: "users.lookupByEmail",
    route: "POST /api/users.lookupByEmail",
    status: "supported",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Looks up seeded users by email.",
  },
  {
    family: "reactions",
    method: "reactions.add",
    route: "POST /api/reactions.add",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts", "slack-events.test.ts"],
    notes: "Adds message reactions and rejects duplicates.",
  },
  {
    family: "reactions",
    method: "reactions.remove",
    route: "POST /api/reactions.remove",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts", "slack-events.test.ts"],
    notes: "Removes message reactions for the auth user.",
  },
  {
    family: "reactions",
    method: "reactions.get",
    route: "POST /api/reactions.get",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Returns reactions for message items only.",
  },
  {
    family: "team",
    method: "team.info",
    route: "POST /api/team.info",
    status: "supported",
    testedBy: ["slack.test.ts", "slack-sdk.test.ts"],
    notes: "Returns seeded workspace metadata.",
  },
  {
    family: "bots",
    method: "bots.info",
    route: "POST /api/bots.info",
    status: "partial",
    testedBy: ["slack-sdk.test.ts"],
    notes: "Returns bot metadata when a bot is seeded.",
  },
  {
    family: "oauth",
    method: "oauth.v2.access",
    route: "POST /api/oauth.v2.access",
    status: "partial",
    testedBy: ["slack.test.ts"],
    notes: "Exchanges emulator auth codes for bot tokens. Full installation modeling is future work.",
  },
  {
    family: "oauth",
    method: "oauth.v2.authorize",
    route: "GET /oauth/v2/authorize",
    status: "partial",
    testedBy: ["slack.test.ts"],
    notes: "Renders emulator user picker and validates configured OAuth apps.",
  },
  {
    family: "oauth",
    method: "oauth.v2.authorize.callback",
    route: "POST /oauth/v2/authorize/callback",
    status: "partial",
    testedBy: ["slack.test.ts"],
    notes: "Stores a temporary code and redirects back to the configured OAuth redirect URI.",
  },
  {
    family: "webhooks",
    method: "incoming_webhook",
    route: "POST /services/:teamId/:botId/:token",
    status: "partial",
    testedBy: ["slack.test.ts", "slack-events.test.ts"],
    notes: "Posts text and rich webhook messages with blocks, attachments, and common formatting fields preserved.",
  },
  {
    family: "inspector",
    method: "message_inspector",
    route: "GET /",
    status: "partial",
    testedBy: ["slack.test.ts"],
    notes: "Shows channels and recent messages.",
  },
  {
    family: "files",
    method: "files.getUploadURLExternal",
    route: "POST /api/files.getUploadURLExternal",
    status: "not_started",
    testedBy: [],
    notes: "Planned for SLACK-8.",
  },
  {
    family: "views",
    method: "views.publish",
    route: "POST /api/views.publish",
    status: "not_started",
    testedBy: [],
    notes: "Planned for SLACK-10.",
  },
];
